version: '3'

services:
  recc-recc:
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
        APP_PORT: 5000
    ports:
      - '5000:5000'
    networks:
      - recc-server
    build: .

networks:
  recc-server:
    name: recc-server_sail
    external: true
